"""Tests for pipeline/gate_schematic.py — the layout pipeline's designs,
drawn as schematics by the PDK's own Verilog importer.

Both preprocessing rules here were found by running the importer against
a real OpenLane netlist and getting a file named `.sch`, so both are
pinned. Neither is a defect in the importer — its own example netlist has
neither a leading comment nor a missing space — they are the difference
between the netlists it was written against and the ones Yosys emits.
"""
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pipeline"))

import gate_schematic  # noqa: E402


# The real first lines of pipeline/designs/counter4's synthesis netlist.
YOSYS = '''/* Generated by Yosys 0.46 (git sha1 e97731b9, clang++ 17.0.6 -fPIC -O3) */

module counter4(clk, rst, en, count);
  wire _00_;
  input clk;
  sky130_fd_sc_hd__a21oi_2 _10_ (
    .A1(en),
    .Y(_04_)
  );
  sky130_fd_sc_hd__dfxtp_2 _20_ (
    .CLK(clk),
    .Q(count[0])
  );
endmodule
'''


class Preprocess(unittest.TestCase):
    def test_the_module_line_gets_the_space_the_importer_splits_on(self):
        """Without it the importer reads the module name from $2 and gets
        `counter4(clk,`, then writes its output to a file called `.sch`."""
        out = gate_schematic.preprocess(YOSYS)
        self.assertIn("module counter4 (clk, rst, en, count);", out)

    def test_the_yosys_banner_comment_is_removed(self):
        """The importer sets RS to ';\\n', so the comment and the module
        declaration land in one record whose $1 is `/*` — the module line
        is never matched and the run produces nothing."""
        out = gate_schematic.preprocess(YOSYS)
        self.assertNotIn("Generated by Yosys", out)
        self.assertTrue(out.startswith("module "), out[:40])

    def test_blank_lines_do_not_survive_into_the_first_record(self):
        self.assertNotIn("\n\n", gate_schematic.preprocess(YOSYS))

    def test_the_cells_themselves_are_untouched(self):
        out = gate_schematic.preprocess(YOSYS)
        self.assertIn("sky130_fd_sc_hd__a21oi_2 _10_ (", out)
        self.assertIn(".Q(count[0])", out)


class Counting(unittest.TestCase):
    def test_it_counts_standard_cell_instances(self):
        self.assertEqual(gate_schematic.cell_count(YOSYS), 2)

    def test_a_netlist_from_another_library_counts_zero(self):
        """The importer's symbols are sky130_fd_sc_hd only; an hs or
        gf180mcu run has nothing to draw with."""
        self.assertEqual(
            gate_schematic.cell_count("sky130_fd_sc_hs__inv_1 x0 ( .A(a) );"), 0)


class Drawability(unittest.TestCase):
    def test_the_cap_is_a_real_measured_number(self):
        # Measured on this repo: ~2.6 KB of SVG per cell, so the cap is
        # roughly a 4 MB drawing. aes (11,616) and riscv32i (5,423) are
        # past it; gcd (280) and spm (224) are not.
        self.assertGreater(gate_schematic.MAX_DRAWABLE_CELLS, 280)
        self.assertLess(gate_schematic.MAX_DRAWABLE_CELLS, 5423)


class NetlistDiscovery(unittest.TestCase):
    def test_a_run_built_with_another_library_is_not_offered(self):
        """Reported rather than drawn wrong: the return is None, and
        convert() turns that into a message naming the reason."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td) / "runs" / "c-hs-strategy" / "06-yosys-synthesis"
            root.mkdir(parents=True)
            (root / "x.nl.v").write_text("sky130_fd_sc_hs__inv_1 x0 ( .A(a) );",
                                          encoding="utf-8")
            self.assertIsNone(
                gate_schematic.find_netlist("x", root.parent.parent / "c-hs-strategy"))

    def test_a_drawable_run_is_found(self):
        with tempfile.TemporaryDirectory() as td:
            run = Path(td) / "c-hd-strategy"
            (run / "06-yosys-synthesis").mkdir(parents=True)
            netlist = run / "06-yosys-synthesis" / "x.nl.v"
            netlist.write_text(YOSYS, encoding="utf-8")
            self.assertEqual(gate_schematic.find_netlist("x", run), netlist)


if __name__ == "__main__":
    unittest.main()
