#!/usr/bin/env python3
"""A schematic view of what the layout pipeline actually built.

The digital half of this repo goes RTL -> synthesis -> placement ->
routing and shows you a GDS render at the end. Between those two there
is a gate netlist that nobody ever looks at, which is the one artifact a
commercial console always lets you open: Innovus and Virtuoso both put a
schematic view on the netlist, because "which cells is this, and what is
connected to what" is a question a layout picture cannot answer.

This closes that gap with the PDK's own converter. sky130A ships
`libs.tech/xschem/xschem_verilog_import/make_sky130_sch_from_verilog.awk`
together with 440 xschem symbols for the sky130_fd_sc_hd standard cells,
so the drawing is made from the real netlist by a tool the PDK
maintains — not by a renderer written here that would be a second thing
able to disagree with it.

Two preprocessing steps are needed, and both were found by running it:

- Yosys writes `module counter4(clk, ...)` with no space before the port
  list. The importer splits records on whitespace and reads the module
  name from $2, so without a space the name becomes `counter4(clk,` and
  the output lands in a file called `.sch`.
- Yosys also opens the file with a `/* Generated by Yosys ... */`
  comment. The importer sets RS to ";\\n", so that comment and the module
  declaration end up in one record whose $1 is `/*` — the module line is
  never matched at all and the run produces an empty schematic.

Neither is a defect in the importer: its own example netlist has neither
a comment nor a missing space. They are the difference between the
netlists it was written against and the ones OpenLane emits, and the
right place to absorb that is here.

Limitation, stated rather than discovered later: the symbol library is
sky130_fd_sc_hd only. A run built with `sky130_fd_sc_hs` or a gf180mcu
library has no symbols to draw with, and this reports that instead of
drawing something wrong.

Usage:
    gate_schematic.py --design counter4
    gate_schematic.py --design counter4 --run-dir designs/counter4/runs/<tag>
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import custom_bridge
from toolchain import platform_args

REPO_ROOT = Path(__file__).resolve().parent.parent
DESIGNS = REPO_ROOT / "pipeline" / "designs"
PDK_ROOT = REPO_ROOT / "pdk"

IMPORTER = "/pdk/sky130A/libs.tech/xschem/xschem_verilog_import/make_sky130_sch_from_verilog.awk"
# The one standard-cell library the importer has symbols for.
DRAWABLE_PREFIX = "sky130_fd_sc_hd__"

# Above this, the drawing is real and useless. Measured on this repo's
# own designs — the SVG runs about 2.6 KB per cell:
#
#   counter4        19 cells ->   48 KB
#   cdc_twoclock    42 cells ->  106 KB
#   spm            224 cells ->  600 KB
#   gcd            280 cells ->  720 KB
#   riscv32i     5,423 cells -> 14.8 MB   (rendered in 15 s)
#   aes         11,616 cells -> 39.0 MB   (rendered in 73 s)
#
# A browser panel cannot show 39 MB of vector, and a reader cannot read
# 11,616 gates on one sheet either — which is why a commercial console
# will not schematic-view a whole SoC in one window. The cap is on cells
# rather than bytes because cells are countable before spending the 73
# seconds, and `force` exists because "too dense to read" is a judgement
# the caller is allowed to overrule.
MAX_DRAWABLE_CELLS = 1500


def find_netlist(design: str, run_dir: Path | None = None) -> Path | None:
    """The synthesis-stage gate netlist to draw.

    Synthesis output rather than `final/nl`, for the same reason
    equiv_check.py gives: the final netlist carries cells inserted after
    synthesis for physical reasons (fill, tap, decap, antenna diodes)
    which have no logic function and would be drawn as a wall of
    unconnected boxes.
    """
    roots = [run_dir] if run_dir else sorted(
        (DESIGNS / design / "runs").glob("*"), reverse=True)
    for root in roots:
        if not root or not root.is_dir():
            continue
        for path in sorted(root.glob("*yosys-synthesis/*.nl.v")):
            if DRAWABLE_PREFIX in path.read_text(encoding="utf-8", errors="ignore"):
                return path
    return None


def preprocess(verilog: str) -> str:
    """Make a Yosys netlist look like what the importer parses.

    See the module docstring for why each of these two is needed; both
    were found by running the importer and getting a file named `.sch`.
    """
    without_comments = re.sub(r"/\*.*?\*/", "", verilog, flags=re.DOTALL)
    lines = [l for l in without_comments.splitlines() if l.strip()]
    spaced = [re.sub(r"^module\s+([A-Za-z0-9_]+)\(", r"module \1 (", l)
              for l in lines]
    return "\n".join(spaced) + "\n"


def cell_count(verilog: str) -> int:
    return len(re.findall(rf"\b{DRAWABLE_PREFIX}\w+\s+\S+\s*\(", verilog))


def convert(design: str, run_dir: Path | None = None,
            out_dir: Path | None = None, timeout: int = 600) -> dict:
    """Netlist -> .sch + .sym, drawn by the PDK's own importer."""
    netlist = find_netlist(design, run_dir)
    if netlist is None:
        return {"design": design, "ok": False,
                "error": "no synthesis netlist with sky130_fd_sc_hd cells under "
                          f"designs/{design}/runs/ — a run built with another "
                          "standard-cell library has no symbols to draw with"}
    if not (shutil.which("docker") and custom_bridge.ensure_xschem_image()):
        return {"design": design, "ok": False,
                "error": "xschem is not installed and its image could not be built"}

    source = netlist.read_text(encoding="utf-8")
    top = netlist.stem.replace(".nl", "")
    out_dir = out_dir or (DESIGNS / design / "sch")
    out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as td:
        work = Path(td)
        (work / f"{top}.v").write_text(preprocess(source), encoding="utf-8")
        argv = ["docker", "run", "--rm", *platform_args(),
                "-v", f"{PDK_ROOT}:/pdk:ro", "-v", f"{work}:/work",
                "-w", "/work", "-e", "PDK_ROOT=/pdk",
                custom_bridge.XSCHEM_IMAGE,
                "awk", "-f", IMPORTER, f"{top}.v"]
        try:
            result = subprocess.run(argv, capture_output=True, text=True,
                                    timeout=timeout, stdin=subprocess.DEVNULL)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return {"design": design, "ok": False, "error": str(exc)}

        produced = {p.name: p for p in work.glob("*.sch")}
        produced.update({p.name: p for p in work.glob("*.sym")})
        # The importer exits 0 having written a file called `.sch` when it
        # could not read the module name, so the name is the verdict.
        wanted = [f"{top}.sch", f"{top}.sym"]
        if not all(name in produced for name in wanted):
            return {"design": design, "ok": False,
                    "error": f"importer wrote {sorted(produced) or 'nothing'}, "
                              f"expected {wanted}",
                    "log": (result.stdout + result.stderr)[-800:]}
        for name in wanted:
            shutil.copy(produced[name], out_dir / name)

    cells = cell_count(source)
    return {"design": design, "ok": True, "top": top,
            "netlist": str(netlist.relative_to(REPO_ROOT)),
            "cells": cells,
            "drawable": cells <= MAX_DRAWABLE_CELLS,
            "schematic": str((out_dir / f"{top}.sch").relative_to(REPO_ROOT)),
            "symbol": str((out_dir / f"{top}.sym").relative_to(REPO_ROOT))}


def convert_cone(design: str, seed: str, depth: int = 4,
                 direction: str = "fanin", run_dir: Path | None = None,
                 out_dir: Path | None = None, max_cells: int = 400,
                 timeout: int = 600) -> dict:
    """One readable sheet out of a design too big to draw whole.

    Same importer, same symbols — only the Verilog handed to it is a
    cone instead of the whole netlist (see netlist_cone.py for why that
    is the answer rather than a bigger canvas).
    """
    import netlist_cone

    extracted = netlist_cone.extract(design, seed, depth, direction, run_dir,
                                     max_cells)
    if not extracted["ok"]:
        return {"design": design, "ok": False, "error": extracted["error"],
                "hint": extracted.get("hint")}
    if not (shutil.which("docker") and custom_bridge.ensure_xschem_image()):
        return {"design": design, "ok": False,
                "error": "xschem is not installed and its image could not be built"}

    top = extracted["module"]
    out_dir = out_dir or (DESIGNS / design / "sch")
    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as td:
        work = Path(td)
        (work / f"{top}.v").write_text(preprocess(extracted["verilog"]),
                                        encoding="utf-8")
        argv = ["docker", "run", "--rm", *platform_args(),
                "-v", f"{PDK_ROOT}:/pdk:ro", "-v", f"{work}:/work",
                "-w", "/work", "-e", "PDK_ROOT=/pdk",
                custom_bridge.XSCHEM_IMAGE, "awk", "-f", IMPORTER, f"{top}.v"]
        try:
            result = subprocess.run(argv, capture_output=True, text=True,
                                    timeout=timeout, stdin=subprocess.DEVNULL)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return {"design": design, "ok": False, "error": str(exc)}
        wanted = [f"{top}.sch", f"{top}.sym"]
        produced = {p.name: p for p in list(work.glob("*.sch")) + list(work.glob("*.sym"))}
        if not all(name in produced for name in wanted):
            return {"design": design, "ok": False,
                    "error": f"importer wrote {sorted(produced) or 'nothing'}, "
                              f"expected {wanted}",
                    "log": (result.stdout + result.stderr)[-800:]}
        for name in wanted:
            shutil.copy(produced[name], out_dir / name)

    return {"design": design, "ok": True, "top": top, "drawable": True,
            "seed": seed, "depth": depth, "direction": direction,
            "directed": extracted["directed"],
            "cells": extracted["cells"], "of_total": extracted["of_total"],
            "truncated": extracted["truncated"],
            "netlist": extracted["netlist"],
            "schematic": str((out_dir / f"{top}.sch").relative_to(REPO_ROOT)),
            "symbol": str((out_dir / f"{top}.sym").relative_to(REPO_ROOT))}


def drawable_designs() -> list[str]:
    """Designs with a netlist this can actually draw, asked not assumed."""
    if not DESIGNS.is_dir():
        return []
    return [d.name for d in sorted(DESIGNS.iterdir())
            if d.is_dir() and find_netlist(d.name) is not None]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--design", default=None,
                    help="omit to list designs that have a drawable netlist")
    ap.add_argument("--run-dir", type=Path, default=None)
    ap.add_argument("--draw", action="store_true", help="also render an SVG")
    ap.add_argument("--seed", default=None,
                    help="draw a cone around this net/instance instead of the "
                          "whole design — the way to see aes or riscv32i")
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--direction", choices=("fanin", "fanout", "both"),
                    default="fanin")
    ap.add_argument("--force", action="store_true",
                    help=f"render even above {MAX_DRAWABLE_CELLS} cells")
    args = ap.parse_args()

    if not args.design:
        for name in drawable_designs():
            print(name)
        return

    out = (convert_cone(args.design, args.seed, args.depth, args.direction,
                        args.run_dir)
           if args.seed else convert(args.design, args.run_dir))
    if not out["ok"]:
        print(f"{args.design}: {out['error']}", file=sys.stderr)
        if out.get("log"):
            print(out["log"], file=sys.stderr)
        sys.exit(1)
    if out.get("seed"):
        print(f"{out['design']} ({out['top']}): {out['cells']} of "
              f"{out['of_total']} cells around {out['seed']}, "
              f"{out['direction']} depth {out['depth']}"
              + ("  (truncated)" if out["truncated"] else "")
              + ("" if out["directed"] else "  (undirected: no Yosys JSON)"))
    else:
        print(f"{out['design']} ({out['top']}): {out['cells']} cells")
    print(f"  from {out['netlist']}")
    print(f"  {out['schematic']}")
    if args.draw and not out["drawable"] and not args.force:
        print(f"  not drawn: {out['cells']} cells is past the "
              f"{MAX_DRAWABLE_CELLS}-cell cap — pass --force to render anyway")
    elif args.draw:
        drawn = custom_bridge.render_schematic(REPO_ROOT / out["schematic"])
        print(f"  {drawn.metadata.get('svg')}" if drawn.ok
              else f"  render failed: {drawn.errors}")


if __name__ == "__main__":
    main()
